[package]
name = "geo"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "geo-service"
path = "src/geo.rs"


[dependencies]
commons = { path = "../../commons" }
tonic = { workspace = true }
prost = { workspace = true }


[build-dependencies]
tonic-build = "0.9"
