[package]
name = "rate"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "rate-service"
path = "src/rate.rs"

[lib]
path = "src/lib.rs"


[dependencies]
commons = { path = "../../commons" }
tonic = { workspace = true }
prost = { workspace = true }


[build-dependencies]
tonic-build = "0.9"
